In [8]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', None],
    'Age': [25, np.nan, 22, 30],
    'City': ['Mumbai', 'Pune', None, 'Delhi']
}

df = pd.DataFrame(data)


# isnull() & .notnull()
# Used to detect missing (null/NaN) values.


print(df.isnull())       # Shows True where values are missing
print(df['Age'].notnull())  # Shows True for non-missing Age values
print("----------------------------------------------------------")
print("dropna()\n")
# dropna()
# Removes rows (or columns) with missing values.



df_cleaned = df.dropna()            # Drops rows where *any* value is NaN
df_cleaned_cols = df.dropna(axis=1) # Drops columns with NaNs

print("----------------------------------------------------------")
print("fillna()\n")
# fillna()
# Fills missing values with a specified value or method.


df_filled = df.fillna({
    'Name': 'Unknown',
    'Age': df['Age'].mean(),
    'City': 'Not Provided'
})

print(df_filled)

print("----------------------------------------------------------")
print("replace()\n")
# replace()
# Replaces specific values in a DataFrame.


df_replaced = df.replace({
    'Mumbai': 'Bombay',
    'Pune': 'Poona'
})
print(df_replaced)

print("----------------------------------------------------------")
print("astype()\n")

# astype()
# Converts data types of columns.


df['Age'] = df['Age'].fillna(0)  # Fill first to avoid error
df['Age'] = df['Age'].astype(int)  # Convert from float to int

print(df)

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3   True  False  False
0     True
1    False
2     True
3     True
Name: Age, dtype: bool
----------------------------------------------------------
dropna()

----------------------------------------------------------
fillna()

      Name        Age          City
0    Alice  25.000000        Mumbai
1      Bob  25.666667          Pune
2  Charlie  22.000000  Not Provided
3  Unknown  30.000000         Delhi
----------------------------------------------------------
replace()

      Name   Age    City
0    Alice  25.0  Bombay
1      Bob   NaN   Poona
2  Charlie  22.0    None
3     None  30.0   Delhi
----------------------------------------------------------
astype()

      Name  Age    City
0    Alice   25  Mumbai
1      Bob    0    Pune
2  Charlie   22    None
3     None   30   Delhi